import 'package:over_react/over_react.dart';

part 'typography.over_react.g.dart';

UiFactory<TypographyProps> Typography = uiFunction((_) {}), _$TypographyConfig);

@Props(keyNamespace: '')
mixin TypographyProps on UiProps {
  @convertJsMapProp
  Map? sx;

  @Deprecated('Use sx.') dynamic alignContent;
  @Deprecated('Use sx.') dynamic alignItems;
  @Deprecated('Use sx.') dynamic alignSelf;
  @Deprecated('Use sx.') dynamic bgcolor;
  @Deprecated('Use sx.') dynamic border;
  @Deprecated('Use sx.') dynamic borderBottom;
  @Deprecated('Use sx.') dynamic borderColor;
  @Deprecated('Use sx.') dynamic borderLeft;
  @Deprecated('Use sx.') dynamic borderRadius;
  @Deprecated('Use sx.') dynamic borderRight;
  @Deprecated('Use sx.') dynamic borderTop;
  @Deprecated('Use sx.') dynamic bottom;
  @Deprecated('Use sx.') dynamic boxShadow;
  @Deprecated('Use sx.') dynamic boxSizing;
  @Deprecated('Use sx.') dynamic color;
  @Deprecated('Use sx.') dynamic columnGap;
  @Deprecated('Use sx.') dynamic display;
  @Deprecated('Use sx.') dynamic displayPrint;
  @Deprecated('Use sx.') dynamic flex;
  @Deprecated('Use sx.') dynamic flexBasis;
  @Deprecated('Use sx.') dynamic flexDirection;
  @Deprecated('Use sx.') dynamic flexGrow;
  @Deprecated('Use sx.') dynamic flexShrink;
  @Deprecated('Use sx.') dynamic flexWrap;
  @Deprecated('Use sx.') dynamic fontFamily;
  @Deprecated('Use sx.') dynamic fontSize;
  @Deprecated('Use sx.') dynamic fontStyle;
  @Deprecated('Use sx.') dynamic fontWeight;
  @Deprecated('Use sx.') dynamic gap;
  @Deprecated('Use sx.') dynamic gridArea;
  @Deprecated('Use sx.') dynamic gridAutoColumns;
  @Deprecated('Use sx.') dynamic gridAutoFlow;
  @Deprecated('Use sx.') dynamic gridAutoRows;
  @Deprecated('Use sx.') dynamic gridColumn;
  @Deprecated('Use sx.') dynamic gridRow;
  @Deprecated('Use sx.') dynamic gridTemplateAreas;
  @Deprecated('Use sx.') dynamic gridTemplateColumns;
  @Deprecated('Use sx.') dynamic gridTemplateRows;
  @Deprecated('Use sx.') dynamic height;
  @Deprecated('Use sx.') dynamic justifyContent;
  @Deprecated('Use sx.') dynamic justifyItems;
  @Deprecated('Use sx.') dynamic justifySelf;
  @Deprecated('Use sx.') dynamic left;
  @Deprecated('Use sx.') dynamic letterSpacing;
  @Deprecated('Use sx.') dynamic lineHeight;
  @Deprecated('Use sx.') dynamic m;
  @Deprecated('Use sx.') dynamic margin;
  @Deprecated('Use sx.') dynamic marginBlock;
  @Deprecated('Use sx.') dynamic marginBlockEnd;
  @Deprecated('Use sx.') dynamic marginBlockStart;
  @Deprecated('Use sx.') dynamic marginBottom;
  @Deprecated('Use sx.') dynamic marginInline;
  @Deprecated('Use sx.') dynamic marginInlineEnd;
  @Deprecated('Use sx.') dynamic marginInlineStart;
  @Deprecated('Use sx.') dynamic marginLeft;
  @Deprecated('Use sx.') dynamic marginRight;
  @Deprecated('Use sx.') dynamic marginTop;
  @Deprecated('Use sx.') dynamic marginX;
  @Deprecated('Use sx.') dynamic marginY;
  @Deprecated('Use sx.') dynamic maxHeight;
  @Deprecated('Use sx.') dynamic maxWidth;
  @Deprecated('Use sx.') dynamic mb;
  @Deprecated('Use sx.') dynamic minHeight;
  @Deprecated('Use sx.') dynamic minWidth;
  @Deprecated('Use sx.') dynamic ml;
  @Deprecated('Use sx.') dynamic mr;
  @Deprecated('Use sx.') dynamic mt;
  @Deprecated('Use sx.') dynamic mx;
  @Deprecated('Use sx.') dynamic my;
  @Deprecated('Use sx.') dynamic order;
  @Deprecated('Use sx.') dynamic overflow;
  @Deprecated('Use sx.') dynamic p;
  @Deprecated('Use sx.') dynamic padding;
  @Deprecated('Use sx.') dynamic paddingBlock;
  @Deprecated('Use sx.') dynamic paddingBlockEnd;
  @Deprecated('Use sx.') dynamic paddingBlockStart;
  @Deprecated('Use sx.') dynamic paddingBottom;
  @Deprecated('Use sx.') dynamic paddingInline;
  @Deprecated('Use sx.') dynamic paddingInlineEnd;
  @Deprecated('Use sx.') dynamic paddingInlineStart;
  @Deprecated('Use sx.') dynamic paddingLeft;
  @Deprecated('Use sx.') dynamic paddingRight;
  @Deprecated('Use sx.') dynamic paddingTop;
  @Deprecated('Use sx.') dynamic paddingX;
  @Deprecated('Use sx.') dynamic paddingY;
  @Deprecated('Use sx.') dynamic pb;
  @Deprecated('Use sx.') dynamic pl;
  @Deprecated('Use sx.') dynamic position;
  @Deprecated('Use sx.') dynamic pr;
  @Deprecated('Use sx.') dynamic pt;
  @Deprecated('Use sx.') dynamic px;
  @Deprecated('Use sx.') dynamic py;
  @Deprecated('Use sx.') dynamic right;
  @Deprecated('Use sx.') dynamic rowGap;
  @Deprecated('Use sx.') dynamic textAlign;
  @Deprecated('Use sx.') dynamic textOverflow;
  @Deprecated('Use sx.') dynamic textTransform;
  @Deprecated('Use sx.') dynamic top;
  @Deprecated('Use sx.') dynamic typography;
  @Deprecated('Use sx.') dynamic visibility;
  @Deprecated('Use sx.') dynamic whiteSpace;
  @Deprecated('Use sx.') dynamic width;
  @Deprecated('Use sx.') dynamic zIndex;
}
